name: CI FOR MVP

on:
  push:
#    branches-ignore:
#      - main
#      - develop

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'testDB'
          mysql user: 'test'
          mysql password: 'testPW'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Create application.properties
        run: |
          cat <<EOT > ./src/main/resources/application.properties
          spring.application.name=ureca

          spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
          spring.datasource.url=jdbc:mysql://localhost:3306/testDB?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
          spring.datasource.username=test
          spring.datasource.password=testPW

          # spring jpa
          spring.jpa.database=mysql
          spring.jpa.properties.hibernate.show_sql=true
          spring.jpa.hibernate.ddl-auto=create-drop
          spring.jpa.properties.hibernate.format_sql=true
          
          spring.data.redis.host=localhost
          spring.data.redis.port=6379
          EOT
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
